quarkus.http.port=8081

# Bases de datos
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/db_auth
quarkus.datasource.username=usuario_cordillera
quarkus.datasource.password=cordillera_pass

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

# JWT

mp.jwt.verify.publickey.location=classpath:publicKey.pem
smallrye.jwt.sign.key.location=classpath:privateKey.pem
mp.jwt.verify.issuer=grupo-cordillera-auth

# Configuración de OpenAPI (Swagger) para testear
quarkus.swagger-ui.always-include=true

# Swagger Security
mp.openapi.extensions.smallrye.security-scheme=jwt
mp.openapi.extensions.smallrye.security-scheme-name=BearerAuth
mp.openapi.extensions.smallrye.security-scheme-description=JWT Authorization
mp.openapi.extensions.smallrye.security-scheme-type=http
mp.openapi.extensions.smallrye.security-scheme-scheme=bearer
mp.openapi.extensions.smallrye.security-scheme-bearer-format=JWT